name: Release

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
    with:
      target: release_apk
      ref: ${{ github.ref }}
    secrets:
      CHECKOUT_TOKEN: ${{ secrets.CHECKOUT_TOKEN }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v8
      with:
        name: release-apk
        path: artifacts/

    - name: Rename artifact
      run: mv artifacts/*.apk "artifacts/AmneziaWG-Plus-${{ github.ref_name }}.apk"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        prerelease: ${{ contains(github.ref_name, '-') }}
        make_latest: ${{ !contains(github.ref_name, '-') }}
        files: artifacts/*.apk
